backend:
  name: github # Switch back to GitHub
  repo: kubecoin-io/kubecoin-website # Ensure this is correct
  branch: main # Ensure this is correct
  base_url: "https://kubecoin.io" # Ensure this is correct
  auth_endpoint: "/api/auth"      # Ensure this is correct
  app_id: "Ov23liNXJUIuHjXxeoeN" # Ensure this is correct

# Keep media settings as they are required
media_folder: "static/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

# Keep the simplified collection for now
collections:
  - name: "test"
    label: "Test"
    folder: "content/_test" # Use a temporary folder
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" } # Added body field back