backend:
  name: github
  repo: kubecoin-io/kubecoin-website
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: blog
    label: Blog
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }