backend:
  name: github
  repo: kubecoin-io/kubecoin-website
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: posts
    label: Blog Posts
    folder: posts
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    folder: pages
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}