backend:
  name: github
  repo: kubecoin-io/kubecoin-website
  branch: main
  base_url: "https://kubecoin.io" # Your site's base URL
  auth_endpoint: "/api/auth"      # Path to your Cloudflare auth function
  app_id: "Ov23liNXJUIuHjXxeoeN" # Add your GitHub OAuth App Client ID here

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: blog
    label: Blog
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }