backend:
  name: test-repo # Use the test backend

collections:
  - name: "test"
    label: "Test"
    folder: "_posts" # test-repo uses predefined folders
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" } # Add body field for test-repo