backend:
  name: test-repo # Use the test backend

# Add required media settings, even if test-repo ignores them
media_folder: "static/uploads" # Or any placeholder path
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey # Use a demo key or placeholder

collections:
  - name: "test"
    label: "Test"
    folder: "_posts" # test-repo uses predefined folders
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" } # Add body field for test-repo