backend:
  name: github
  repo: kubecoin-io/kubecoin-website # Make sure this is correct
  branch: main
  base_url: "https://kubecoin.io"
  auth_endpoint: "/api/auth"
  app_id: "Ov23liNXJUIuHjXxeoeN" # Make sure this is correct

media_folder: "content/uploads" # Required
public_folder: "/uploads"      # Required

collections: # Must have at least one collection
  - name: "test"
    label: "Test"
    folder: "content/_test" # Use a temporary folder
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }